# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e4d296e1c65fa946f00b9decdef941d8b6fe7d5c9d7eecaa1e5041695f8d2d6dc4cbadbbdfb7499666acd072563acf86fe06556528a1895b883810587fa787

test:
  secret_key_base: 12957b427cb22c9e1dcd714272e0cbc5b546ee6865778879354cd879ec9af3e4675d08d1ecb4b446f8f39581e14370e6411fafa171e5e358aca89c4983f70cb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
